### ISSUE TITLE
如果给skynet用，线程安全情况是怎样的？

### ISSUE THREAD

**Issue by sniper00** [jinjiazhang/protolua#1]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by jinjiazhang** [comment]
protobuf是线程安全的，所以protolua的encode、decode对同一个luaState来说也是线程安全的，如果有多个luaState的话parse将枚举解析成lua的table的功能将会是当前luaState可用

**Comment by sniper00** [comment]
也就是说除了枚举， 其它的线程安全行为和 云风的 pbc 一致？

**Comment by jinjiazhang** [comment]
是的，除了parse其他的接口都是线程安全的

**Comment by sniper00** [comment]
好的
